# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - SFolio-App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    environment: Production

    permissions:
      contents: read #This is required for actions/checkout
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      - name: Restore dependencies
        run: dotnet restore StudentPortfolio/StudentPortfolio.csproj

      - name: Restore local tools
        run: dotnet tool restore
        working-directory: ./StudentPortfolio

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ./StudentPortfolio

      - name: Update database
        run: |
          dotnet ef database update -c StudentPortfolioContext -p StudentPortfolio.csproj -s StudentPortfolio.csproj
        working-directory: ./StudentPortfolio
        env:
          ASPNETCORE_ENVIRONMENT: Production
          ConnectionStrings__DbConnection: ${{ secrets.DBCONNECTION }}

      - name: dotnet publish
        working-directory: ./StudentPortfolio
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/StudentPortfolio_App"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/StudentPortfolio_App

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_03CEB28C7E7045BCB0C77D7AFDCCD662 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0953215F733E4524B12BAD140FEECE10 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E6547BC994A24ECD820BA22B2E760D6A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "SFolio-App"
          slot-name: "Production"
          package: .
